import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="w-screen sticky overflow-hidden top-0">
          <nav className="w-[20%] flex justify-between list-none p-[10px]">
            <Link href={"/"}>Home</Link>
            <Link href={"/contacts"}>Contacts</Link>
            <Link href={"login"}>Login</Link>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
